### ISSUE TITLE
Is there a mistake in README?

### ISSUE THREAD

**Issue by Roger-luo** [jakebolewski/PicoSAT.jl#1]
> Both methods take the following optional keyword arguments:
> 
> ```
> vars - the number of variables
> verbose - prints solver logs to STDOUT when verbose > 0 with increasing detail.
> proplimit - helps to bound the execution time. The number of propagations and the solution time are roughly linearly related. A value of -1 (default) allows for an unbounded number of propagations.
> ```
> 
> solve(clauses; vars::Integer=-1, verbose::Integer=0, proplimit::Integer=0)

it seems the default value for proplimit is -1 but it's 0 in the code?
and what's the default value -1 for vars mean?

correct me if I made a mistake :-) please

**Comment by jakebolewski** [comment]
It took a while, but thanks  this is fixed!
