### ISSUE TITLE
attobot

### ISSUE THREAD

**Issue by CarloLucibello** [jakebolewski/PicoSAT.jl#10]
@jakebolewski could you activate attobot for this repo?
https://github.com/attobot/attobot

**Comment by jakebolewski** [comment]
Done.

@CarloLucibello is there a relevant organization I could transfer ownership of this repo?  Otherwise I can add you as an admin if you want to maintain it.

**Comment by CarloLucibello** [comment]
JuliaOpt and JuliaNLsolvers orgs seem to be focused around Jump/MathProgBase and Optim respectively, 
it's not clear if they would accept non-related packages. I would gladly maintain the package and eventually move it to a fitting org at the first opportunity.
