### ISSUE TITLE
tag new release

### ISSUE THREAD

**Issue by MaximeBouton** [jakebolewski/PicoSAT.jl#15]
Would it be possible to tag a new release with the new cross platform support? 
Thanks

**Comment by CarloLucibello** [comment]
just waiting for the previous repo maintainer to add Registrator, see #16

**Comment by MaximeBouton** [comment]
Hi, would it be possible to tag a new release with the BB support? Thanks

**Comment by CarloLucibello** [comment]
@jakebolewski is awol, and I don't have the permissions to activate Registrator and TagBot for this repo. If we don't hear from him soon I fear we will be forced to fork the repo,

**Comment by MaximeBouton** [comment]
It would be nice to transfer ownership to a julia organization to ensure maintenance, do you know any that would fit?

cc @tomerarnon

**Comment by MaximeBouton** [comment]
bump

**Comment by CarloLucibello** [comment]
@jakebolewski could you activate the Registrator app for this repo?https://github.com/JuliaRegistries/Registrator.jl
