### ISSUE TITLE
Transfer to an org

### ISSUE THREAD

**Issue by ViralBShah** [jakebolewski/PicoSAT.jl#18]
@jakebolewski Some discussion on slack came up - where people want to be able to work on the package and maintain it. Would it be possible for you to transfer it to the https://github.com/sisl org?

cc @CarloLucibello

**Comment by StefanKarpinski** [comment]
cc @simonbyrne

**Comment by jakebolewski** [comment]
Yes I can do that.  I would prefer an Julia specific organization if possible as I think it's a bit more maintainable that way, but sisl seems a good second choice if there is no obvious Julia organization.

**Comment by jakebolewski** [comment]
To do the transfer I will need to be added to the organization temporarily in any case.

**Comment by CarloLucibello** [comment]
@tomerarnon should be able to manage the transfer

**Comment by CarloLucibello** [comment]
possible alternatives that came to my mind are JuliaNLSolvers and JUMP org, but neither seems a perfect match

**Comment by jakebolewski** [comment]
Ok cool, let me know and I'll make the transfer once I am added to an org (which seems necessary, just attempted).

**Comment by tomerarnon** [comment]
@mykelk, could you add @jakebolewski to SISL so that he can transfer PicoSAT?

**Comment by mykelk** [comment]
@jakebolewski , welcome to SISL! ;-)

**Comment by jakebolewski** [comment]
@mykelk I think I need temporary escalated privileges

> You don’t have the permission to create public repositories on sisl

**Comment by jakebolewski** [comment]
Nevermind, seems like a consistency issue on Github's side.  Should be completed in a few minutes.

**Comment by mykelk** [comment]
Yay! It worked!

**Comment by jakebolewski** [comment]
Great!
