### ISSUE TITLE
build with BinaryBuilder

### ISSUE THREAD

**Issue by CarloLucibello** [jakebolewski/PicoSAT.jl#6]

**Comment by MaximeBouton** [comment]
Hello, 
I took a shot at building PicoSAT with BinaryBuilder, it seems to work on Mac, Linux (64 and 32 bits), Windows (64 and 32bits): https://github.com/MaximeBouton/PicoSATBuilder/tree/master
Hopefully switching to using BB in the deps should fix #7 as well.

**Comment by CarloLucibello** [comment]
closed by #6
